### ISSUE TITLE
$URL/config/ gives 500 Error

### ISSUE THREAD

**Issue by teiko** [aforty/sabnzbd-knockstrap#1]
On Debian Wheezy with sabnzbdplus in Version  0.6.15-1 from Debian Repository ( CherryPy 3.2.0 / Version: 2.3.0-3 from Repository) there is:

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/share/sabnzbdplus/cherrypy/_cprequest.py", line 618, in respond
    cherrypy.response.body = self.handler()
  File "/usr/share/sabnzbdplus/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/share/sabnzbdplus/sabnzbd/interface.py", line 1015, in index
    filter=FILTER, searchList=[conf], compilerSettings=DIRECTIVES)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1259, in __init__
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/usr/lib/python2.7/dist-packages/Cheetah/Template.py", line 1546, in _compile
    self._fileMtime = os.path.getmtime(file)
  File "/usr/lib/python2.7/genericpath.py", line 54, in getmtime
    return os.stat(filename).st_mtime
OSError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/share/sabnzbdplus/interfaces/Knockstrap/templates/config.tmpl'
```

**Comment by aforty** [comment]
Hi teiko,
Knockstrap requires SABnzbd 7.x. This is because starting in 7.x a theme can no longer override the config pages, thus there's I didn't include them. This causes an issue in your build where it's looking specifically for configuration page templates (config.tmpl in your error) that don't exist. 

So upgrade to 7.x and you should be all set. Hope that's an option for you, if not, sorry.
